name: Push to Replicate

on:
  push:
    branches:
      - main

jobs:
  my-job:
      #runs-on: auto-cog
      runs-on: ubuntu-latest

      steps:
        - name: Maximize build space
          uses: AdityaGarg8/remove-unwanted-software@v1
          with:
            remove-android: 'true'
            remove-dotnet: 'true'
            remove-haskell: 'true'
            remove-docker-images: 'true'
            remove-codeql: 'true'
            temp-reserve-mb: '100'
            swap-size-mb: '4096'

        - name: Delete huge unnecessary tools folder
          run: rm -rf /opt/hostedtoolcache

        - name: Free space
          run: |
            echo "Free space:"
            df -h

        - name: Check out code
          uses: actions/checkout@v3

        - name: Setup Cog
          uses: replicate/setup-cog@v1.0.3
          with:
            token: ${{ secrets.REPLICATE_API_TOKEN }}
            install-cuda: true

        - name: permission
          run: (chmod -R 777 script/download-weights) && pwd && ls

        - name: Download weights
          run: wget https://usa-goyor.oss-us-west-1.aliyuncs.com/public/v2-1_768-nonema-pruned.safetensors

        - name: Download weights
          run: cog run script/download-weights
          #下载模型权重

        - name: Push to Replicate
          run: |
            cog push r8.im/benlin924/test5
